/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del servicio */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predicciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Predicción de visitantes (hoy a hoy+2) */
        get: operations["getPredicciones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clima/actual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clima actual en la cueva */
        get: operations["getClimaActual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/historico/mensual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico sintético agregado por mes */
        get: operations["getHistoricoMensual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versión y coeficientes del modelo */
        get: operations["getModelo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @example a1b2c3d */
            version: string;
        };
        Factor: {
            valor: number;
            razon: string;
        };
        Factores: {
            base_diaria: number;
            temporada: components["schemas"]["Factor"];
            dia_semana: components["schemas"]["Factor"];
            feriado: components["schemas"]["Factor"];
            clima: components["schemas"]["Factor"];
            tope_capacidad_aplicado: boolean;
        };
        ClimaDia: {
            condicion: string;
            codigo_condicion: number;
            /** Format: uri */
            icono_url?: string;
            temp_max_c: number;
            temp_min_c: number;
            precipitacion_mm: number;
            probabilidad_lluvia: number;
        };
        Advertencia: {
            /** @enum {string} */
            codigo: "LLUVIA_EXTREMA" | "TORMENTA" | "ALERTA_OFICIAL" | "CLIMA_NO_DISPONIBLE";
            mensaje: string;
        };
        Prediccion: {
            /** Format: date */
            fecha: string;
            visitantes_estimados: number;
            rango: {
                min: number;
                max: number;
            };
            /** @enum {string} */
            nivel_afluencia: "Baja" | "Media" | "Alta" | "Muy alta";
            clima_disponible: boolean;
            clima?: components["schemas"]["ClimaDia"] | null;
            factores: components["schemas"]["Factores"];
            advertencias: components["schemas"]["Advertencia"][];
        };
        PrediccionesResponse: {
            ubicacion: {
                nombre?: string;
                lat?: number;
                lon?: number;
            };
            /** @example reglas-v1 */
            version_modelo: string;
            /** @constant */
            datos_sinteticos: true;
            /** Format: date-time */
            generado_en: string;
            predicciones: components["schemas"]["Prediccion"][];
            /** @constant */
            atribucion: "Powered by WeatherAPI.com";
        };
        ClimaActual: {
            temp_c: number;
            sensacion_c?: number;
            condicion: string;
            /** Format: uri */
            icono_url?: string;
            humedad: number;
            precipitacion_mm?: number;
            /** Format: date-time */
            actualizado_en: string;
        };
        HistoricoMensual: {
            /** @constant */
            datos_sinteticos: true;
            serie: {
                mes: string;
                visitantes: number;
                promedio_diario: number;
            }[];
        };
        Modelo: {
            version_modelo: string;
            base_diaria: number;
            capacidad_diaria: number;
            coeficientes: {
                [key: string]: unknown;
            };
        };
        Error: {
            error: {
                /** @enum {string} */
                codigo: "FECHA_INVALIDA" | "FECHA_FUERA_DE_RANGO" | "PARAMETRO_INVALIDO" | "CLIMA_NO_DISPONIBLE" | "ERROR_INTERNO";
                mensaje: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getPredicciones: {
        parameters: {
            query?: {
                /** @description Fecha única (YYYY-MM-DD). Si se omite, devuelve los 3 días. */
                fecha?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Predicciones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrediccionesResponse"];
                };
            };
            /** @description Fecha inválida o fuera de rango */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getClimaActual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clima actual */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClimaActual"];
                };
            };
            /** @description WeatherAPI no disponible y sin caché */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getHistoricoMensual: {
        parameters: {
            query?: {
                meses?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serie mensual */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricoMensual"];
                };
            };
            /** @description Parámetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getModelo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Modelo vigente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Modelo"];
                };
            };
        };
    };
}
